name: dancephotographer
favicon: null
layout_spectrum: 0.1607252557296306
typography_spectrum: 0.8543651956133544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f908a'
    - '#ffffff'
    - '#b6b6b6'
    - '#4f524b'
    - '#080501'
  brandStrength: 0.8125
  lightness: 0.747714206809178
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
